### ISSUE TITLE
Fix ddns pod counts

### ISSUE THREAD

**Issue by npawelek** [npawelek/home-ops#46]
Successful jobs are limited, but there still appears to be a growing number of completed pods not being cleaned up.

**Comment by npawelek** [comment]
For whatever, the cronjob is identical to the original cluster built on k8s. I wonder if this is a weird k3s-ism?

**Comment by npawelek** [comment]
```
[k8s-gitops]$ k get cronjobs.batch -n aws-ddns aws-ddns -oyaml | yq .spec                                                                                                                                                                                                                                                              master  ✱
concurrencyPolicy: Forbid
failedJobsHistoryLimit: 1
jobTemplate:
  metadata:
    creationTimestamp: null
  spec:
    backoffLimit: 6
    template:
      metadata:
        creationTimestamp: null
        labels:
          app.kubernetes.io/instance: aws-ddns
          app.kubernetes.io/name: aws-ddns
      spec:
        automountServiceAccountToken: true
        containers:
          - command:
              - /bin/sh
              - /app/aws-ddns.sh
            envFrom:
              - secretRef:
                  name: aws-ddns-secrets
            image: public.ecr.aws/hashicorp/terraform:1.4.6@sha256:1ab70aa9b5dcc007d1d908c972405e2623490a51843a500682809013a4d21699
            imagePullPolicy: IfNotPresent
            name: aws-ddns
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
              - mountPath: /app/backend.tf
                name: backend
                readOnly: true
                subPath: backend.tf
              - mountPath: /app/aws-ddns.sh
                name: config
                readOnly: true
                subPath: aws-ddns.sh
              - mountPath: /app/main.tf
                name: terraform
                readOnly: true
                subPath: main.tf
        dnsPolicy: ClusterFirst
        enableServiceLinks: true
        restartPolicy: Never
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: default
        serviceAccountName: default
        terminationGracePeriodSeconds: 30
        volumes:
          - name: backend
            secret:
              defaultMode: 420
              secretName: aws-ddns-tf-backend
          - configMap:
              defaultMode: 509
              name: aws-ddns-configmap
            name: config
          - configMap:
              defaultMode: 420
              name: tf-configmap
            name: terraform
schedule: '*/15 * * * *'
startingDeadlineSeconds: 30
successfulJobsHistoryLimit: 8
suspend: false
```

```
[home-ops]$ k get cronjob -n aws-ddns aws-ddns -oyaml | yq .spec                                                                                                                                                                                                                                                                               main  ✱
concurrencyPolicy: Forbid
failedJobsHistoryLimit: 1
jobTemplate:
  metadata:
    creationTimestamp: null
  spec:
    backoffLimit: 6
    template:
      metadata:
        creationTimestamp: null
        labels:
          app.kubernetes.io/instance: aws-ddns
          app.kubernetes.io/name: aws-ddns
      spec:
        automountServiceAccountToken: true
        containers:
          - command:
              - /bin/sh
              - /app/aws-ddns.sh
            envFrom:
              - secretRef:
                  name: aws-ddns-secret
            image: public.ecr.aws/hashicorp/terraform:1.4.6@sha256:1ab70aa9b5dcc007d1d908c972405e2623490a51843a500682809013a4d21699
            imagePullPolicy: IfNotPresent
            name: aws-ddns
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
              - mountPath: /app/backend.tf
                name: backend
                readOnly: true
                subPath: backend.tf
              - mountPath: /app/aws-ddns.sh
                name: config
                readOnly: true
                subPath: aws-ddns.sh
              - mountPath: /app/main.tf
                name: terraform
                readOnly: true
                subPath: main.tf
        dnsPolicy: ClusterFirst
        enableServiceLinks: true
        restartPolicy: Never
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: default
        serviceAccountName: default
        terminationGracePeriodSeconds: 30
        volumes:
          - name: backend
            secret:
              defaultMode: 420
              secretName: aws-ddns-secret-backend
          - configMap:
              defaultMode: 509
              name: aws-ddns-configmap
            name: config
          - configMap:
              defaultMode: 420
              name: tf-configmap
            name: terraform
schedule: '*/15 * * * *'
startingDeadlineSeconds: 30
successfulJobsHistoryLimit: 1
suspend: false
```
